services:

  postgres:
    image: postgres:17
    container_name: soc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: enterprise_ai_soc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: soc-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: soc-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    container_name: soc-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: