name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t enterprise-ai-soc-backend ./backend

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Scan Docker Image
        run: |
          trivy image enterprise-ai-soc-backend

      - name: Scan Filesystem
        run: |
          trivy fs .