name: Security Scan

on:
  push:

jobs:

  security:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r backend || true

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config auto backend || true